apiVersion: apps/v1 ## extensions/v1beta1 ## apiextensions.k8s.io/v1beta1 ##  
kind: Deployment
metadata:
  labels:
    app: keyvaultreader
    aadpodidbinding: keyvaultaccess
  name: keyvaultreader  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvaultreader      
  template:
    metadata:
      labels:
        app: keyvaultreader
        aadpodidbinding: keyvaultaccess
    spec:
      containers:
      - name: keyvaultreader
        image: "jpjofresm/keyvaultreader:v0.1"
        env:        
        - name: KeyVaultName
          value: "identity-fcm-keyvault2kubernetes"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: keyvaultreader-svc
spec:
    type: LoadBalancer
    selector:
        app: keyvaultreader
    ports:
    - port: 80