// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_service.proto

package com.jpjofre.tutorial.demo.service;

public final class GreetingService {
  private GreetingService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jpjofre_tutorial_demo_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jpjofre_tutorial_demo_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jpjofre_tutorial_demo_grpc_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jpjofre_tutorial_demo_grpc_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023hello_service.proto\022\036com.jpjofre.tutor" +
      "ial.demo.grpc\"(\n\014HelloRequest\022\014\n\004name\030\001 " +
      "\001(\t\022\n\n\002id\030\002 \001(\005\" \n\rHelloResponse\022\017\n\007mess" +
      "age\030\001 \001(\t2w\n\014HelloService\022g\n\010sayHello\022,." +
      "com.jpjofre.tutorial.demo.grpc.HelloRequ" +
      "est\032-.com.jpjofre.tutorial.demo.grpc.Hel" +
      "loResponseB6\n!com.jpjofre.tutorial.demo." +
      "serviceB\017GreetingServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_jpjofre_tutorial_demo_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jpjofre_tutorial_demo_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jpjofre_tutorial_demo_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_com_jpjofre_tutorial_demo_grpc_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jpjofre_tutorial_demo_grpc_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jpjofre_tutorial_demo_grpc_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
