// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_service.proto

package com.jpjofre.tutorial.demo.service;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jpjofre.tutorial.demo.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();
}
