version: '3'
services:
  server:
    image: nginx:1.19.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/usr/share/nginx/html
      - ./nginx/changemanager.fcm.msftcloudes.com.crt:/etc/nginx/changemanager.fcm.msftcloudes.com.crt 
      - ./nginx/changemanager.fcm.msftcloudes.com.key:/etc/nginx/changemanager.fcm.msftcloudes.com.key 
    ports:
    - "127.0.0.1:8704:80"
    - "127.0.0.1:44333:443"