FROM nginx:1.19.4
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./site /usr/share/nginx/html
COPY ./nginx/changemanager.fcm.msftcloudes.com.crt /etc/nginx/changemanager.fcm.msftcloudes.com.crt
COPY ./nginx/changemanager.fcm.msftcloudes.com.key /etc/nginx/changemanager.fcm.msftcloudes.com.key 
